-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "bets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"deadlineAt" timestamp with time zone NOT NULL,
	"status" integer,
	"participants" integer DEFAULT 0 NOT NULL,
	"amount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "betEntries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""betEntries_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"optionId" integer,
	"userId" integer,
	"amount" integer NOT NULL,
	"isWinner" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "betEntries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "trades" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trades_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supplierId" integer,
	"customerId" integer,
	"service" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"deadlineAt" timestamp with time zone NOT NULL,
	"confirmedAt" timestamp with time zone,
	"price" integer NOT NULL,
	"acceptedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "trades" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "status" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"role" integer
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "userWallets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""userWallets_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"balance" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "userWallets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "betOptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""betDetails_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"betId" integer,
	"description" text NOT NULL,
	"amount" integer NOT NULL,
	"isWinner" boolean DEFAULT false NOT NULL,
	"quote" real NOT NULL
);
--> statement-breakpoint
ALTER TABLE "betOptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "bets" ADD CONSTRAINT "bets_status_fkey" FOREIGN KEY ("status") REFERENCES "public"."status"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "betEntries" ADD CONSTRAINT "betEntries_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "public"."betOptions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "betEntries" ADD CONSTRAINT "betEntries_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "trades" ADD CONSTRAINT "trades_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "trades" ADD CONSTRAINT "trades_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."roles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "userWallets" ADD CONSTRAINT "userWallets_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "betOptions" ADD CONSTRAINT "betDetails_betId_fkey" FOREIGN KEY ("betId") REFERENCES "public"."bets"("id") ON DELETE restrict ON UPDATE cascade;
*/